### PR TITLE
Add fake server & basic tests against it

### PR DESCRIPTION
**Pull request by ezheidtmann**
Not ready to merge! Need guidance on the following details:

 * Should additional dependencies be added to `setup.py`?
 * How would you like to include dependences for testing, such as `requests_mock`?
 * Can test discovery be done better?

Tests can be run with `python -m unittest discover mds.tests`, from the repo root.

This PR adds the following:

 * A small Flask server implementing `trips` and `status_changes` endpoints with fixed object lists, with partial support for filters and pagination
 * A GET-only adapter between `requests_mock` and a flask app
 * An API test case which uses the Flask app & mock adapter to check the depagination support in `ProviderClient`

### CODE REVIEW

**Comment by thekaveman** [comment]
This is really cool! Thank you for your efforts @ezheidtmann.

Regarding your points of clarification: #15 was more of a "cry for help" from me, as I have *very* little (read: none) experience with writing tests for Python projects. 

Tagging @hunterowens @ian-r-rose who may be able to weigh in with their thoughts. I am open to whatever best-practices or standard approaches there are to the questions above.

**Comment by ezheidtmann** [comment]
Great. I've usually added tests either to an existing project or within Django, with has an opinionated approach and a custom test runner, so I'm not an expert on the Python community customs here.

**Comment by thekaveman** [comment]
Tagging @johnclary as well, since he seems to have a ton of Python experience (yes, I stalked your profile John!)

**Comment by ezheidtmann** [comment]
Rebased on #46 and `dev` branch

**Comment by ezheidtmann** [comment]
Just pushed 1) changes to `ProviderClient` to emphasize iteration, and 2) a test for the non-overlapping trips query problem

**Comment by thekaveman** [comment]
Hey @ezheidtmann... i made some comments over in your other #46.

The [latest release](https://github.com/CityofSantaMonica/mds-provider/releases/tag/0.4.0) has evolved this library and taken into consideration many of the points you made over these PR conversations, so thank you. Closing this PR but would welcome new work on top of `master`.

**Pull request closed without merging**
