### PR TITLE
Conform to spec

### LINKED ISSUE #3: Spec inconsistencies in generated data
Thanks to @ian-r-rose for doing some initial JSON Schema testing against the generated data coming out of `fake`!

Per https://github.com/CityofSantaMonica/mobility-data-specification/pull/1#issuecomment-423023315, there are a few spec inconsistencies to address:

1.
```python
jsonschema.exceptions.ValidationError: 'accuracy' is a required property
```
2.
```python
jsonschema.exceptions.ValidationError: 845.9042534919543 is not of type 'integer'

Failed validating 'type' in schema['properties']['data']['properties']['trips']['items']['properties']['trip_duration']:
```
3.
```python
jsonschema.exceptions.ValidationError: 2798.1217587696774 is not of type 'integer'

Failed validating 'type' in schema['properties']['data']['properties']['trips']['items']['properties']['trip_distance']:
```

### PR DESCRIPTION
**Pull request by ian-r-rose**
1. Draws accuracy from a [Rayleigh distribution](https://en.wikipedia.org/wiki/Rayleigh_distribution) with mode around 5 meters. May or may not be reasonable, but a fine place to start, I think.
2. Casts properties to an integer as the spec demands. I think the spec should probably relax on this front and allow floating point numbers, but this is what it says for now.

I have *not* updated the `event_location` field to be a `Point`, since the spec does not say that just yet.

Edit: whoops, I see that the spec does now specify point.

Fixes #3

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Okay, `Point` is fixed.

**Comment by thekaveman** [comment]
I'd honestly like us to standardize around `Feature` and `FeatureCollection` in all of these cases, as hinted at in CityOfLosAngeles/mobility-data-specification#74 and proposed in https://github.com/CityOfLosAngeles/mobility-data-specification#73. This would allow `accuracy` and other related properties to co-exist with the geo-data in an easily extensible manner. It also follows from our (buried) [discussion on the JSON Schema work](https://github.com/CityofSantaMonica/mobility-data-specification/pull/1#discussion_r218984324)

**Comment by ian-r-rose** [comment]
Ah, I misunderstood. I can revert that last commit, or we can hang out here until CityOfLosAngeles/mobility-data-specification#74 is resolved.

**Comment by thekaveman** [comment]
Yeah...that last comment got lost in there. I'm hoping we'll have that issue tied up in the next few days, but I'll leave it up to you. I'm good to merge the other changes if you want to revert, or I'm good to wait it out as things may still be changing...

**Comment by thekaveman** [comment]
@ian-r-rose can you revert that last commit, given the latest developments in MDS? Then I can get the other changes merged in.

**Comment by ian-r-rose** [comment]
Yep, reverted!

**Pull request merged**
